<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AuditLog\**" />
    <Compile Remove="Models\**" />
    <Content Remove="AuditLog\**" />
    <Content Remove="Models\**" />
    <EmbeddedResource Remove="AuditLog\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="AuditLog\**" />
    <None Remove="Models\**" />
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
    <PackageReference Include="MudBlazor" Version="9.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MesCore\Promatis.Net.MES.Service\Promatis.Net.MES.Service.csproj" />
    <ProjectReference Include="..\Configuration\Promatis.Net.Configuration.csproj" />
    <ProjectReference Include="..\Service\Promatis.Net.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\AuditLogs\" />
  </ItemGroup>

</Project>
