<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8" />
    <PackageReference Include="MudBlazor" Version="9.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\MesCore\Promatis.Net.MES.UI\Promatis.Net.MES.UI.csproj" />
    <ProjectReference Include="..\Promatis.Net.MES.DCA.Service\Promatis.Net.MES.DCA.Service.csproj" />
  </ItemGroup>

</Project>
