<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="UnitBase\**" />
    <Content Remove="UnitBase\**" />
    <EmbeddedResource Remove="UnitBase\**" />
    <None Remove="UnitBase\**" />
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8" />
    <PackageReference Include="MudBlazor" Version="9.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Configuration.Web\Promatis.Net.Configuration.Web.csproj" />
    <ProjectReference Include="..\..\Core\Promatis.Net.UI\Promatis.Net.UI.csproj" />
    <ProjectReference Include="..\Promatis.Net.MES.Service\Promatis.Net.MES.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\UnitOfMeasurements\Card\" />
  </ItemGroup>

</Project>
