// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Promatis.Net.Test.MDM.Data;

#nullable disable

namespace Promatis.Net.Test.MDM.DataInit.Migrations
{
    [DbContext(typeof(AppApplicationDbContext))]
    partial class AppApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("test")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Promatis.Net.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", "test");
                });

            modelBuilder.Entity("Promatis.Net.MES.Domain.UnitBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ParentId");

                    b.ToTable("Units", "test");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.DepartmentUnit", b =>
                {
                    b.HasBaseType("Promatis.Net.MES.Domain.UnitBase");

                    b.ToTable("DepartmentUnits", "test");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.PositionUnit", b =>
                {
                    b.HasBaseType("Promatis.Net.MES.Domain.UnitBase");

                    b.ToTable("PositionUnits", "test");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.ProductionUnit", b =>
                {
                    b.HasBaseType("Promatis.Net.MES.Domain.UnitBase");

                    b.ToTable("ProductionUnits", "test");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.StorageUnit", b =>
                {
                    b.HasBaseType("Promatis.Net.MES.Domain.UnitBase");

                    b.ToTable("StorageUnits", "test");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.TransportUnit", b =>
                {
                    b.HasBaseType("Promatis.Net.MES.Domain.UnitBase");

                    b.ToTable("TransportUnits", "test");
                });

            modelBuilder.Entity("Promatis.Net.MES.Domain.UnitBase", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.DepartmentUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("Promatis.Net.Test.MDM.Domain.DepartmentUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.PositionUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("Promatis.Net.Test.MDM.Domain.PositionUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.ProductionUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("Promatis.Net.Test.MDM.Domain.ProductionUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.StorageUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("Promatis.Net.Test.MDM.Domain.StorageUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.TransportUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("Promatis.Net.Test.MDM.Domain.TransportUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promatis.Net.MES.Domain.UnitBase", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
