// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Promatis.Net.Test.MDM.Data;

#nullable disable

namespace Promatis.Net.Test.MDM.DataInit.Migrations
{
    [DbContext(typeof(MdmApplicationDbContext))]
    partial class MdmApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mdm")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Promatis.Net.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", "mdm");
                });

            modelBuilder.Entity("Promatis.Net.MES.Domain.UnitBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.ToTable("Units", "mdm");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Promatis.Net.MES.MDM.Domain.TechnologicalOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.ToTable("TechnologicalOperation", "mdm");
                });

            modelBuilder.Entity("Promatis.Net.MES.MDM.Domain.TechnologicalOperationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("OperationId");

                    b.HasIndex("UnitId");

                    b.ToTable("TechnologicalOperationUnit", "mdm");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.DepartmentUnit", b =>
                {
                    b.HasBaseType("Promatis.Net.MES.Domain.UnitBase");

                    b.ToTable("DepartmentUnits", "mdm");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.PositionUnit", b =>
                {
                    b.HasBaseType("Promatis.Net.MES.Domain.UnitBase");

                    b.ToTable("PositionUnits", "mdm");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.ProductionUnit", b =>
                {
                    b.HasBaseType("Promatis.Net.MES.Domain.UnitBase");

                    b.ToTable("ProductionUnits", "mdm");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.StorageUnit", b =>
                {
                    b.HasBaseType("Promatis.Net.MES.Domain.UnitBase");

                    b.ToTable("StorageUnits", "mdm");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.TransportUnit", b =>
                {
                    b.HasBaseType("Promatis.Net.MES.Domain.UnitBase");

                    b.ToTable("TransportUnits", "mdm");
                });

            modelBuilder.Entity("Promatis.Net.MES.MDM.Domain.TechnologicalOperationUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.MDM.Domain.TechnologicalOperation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.DepartmentUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("Promatis.Net.Test.MDM.Domain.DepartmentUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.PositionUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("Promatis.Net.Test.MDM.Domain.PositionUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.ProductionUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("Promatis.Net.Test.MDM.Domain.ProductionUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.StorageUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("Promatis.Net.Test.MDM.Domain.StorageUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Promatis.Net.Test.MDM.Domain.TransportUnit", b =>
                {
                    b.HasOne("Promatis.Net.MES.Domain.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("Promatis.Net.Test.MDM.Domain.TransportUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
