<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\MesCore\Promatis.Net.MES.Domain\Promatis.Net.MES.Domain.csproj" />
    <ProjectReference Include="..\Promatis.Net.MES.MDM.Domain.Interface\Promatis.Net.MES.MDM.Domain.Interface.csproj" />
  </ItemGroup>

</Project>
