<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\MesCore\Promatis.Net.MES.Configuration\Promatis.Net.MES.Configuration.csproj" />
    <ProjectReference Include="..\Promatis.Net.MES.DCA.Service\Promatis.Net.MES.DCA.Service.csproj" />
  </ItemGroup>

</Project>
