<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Mes\MDM\Promatis.Net.MES.MDM.Service\Promatis.Net.MES.MDM.Service.csproj" />
    <ProjectReference Include="..\Promatis.Net.Test.MDM.Data\Promatis.Net.Test.MDM.Data.csproj" />
  </ItemGroup>

</Project>
